"""Constants for Quran data: surah metadata, reciter info, and verse counts."""

SURAH_DATA = (
    {
        "name_arabic": "الفاتحة",
        "name_english": "The Opening",
        "name_transliteration": "Al-Fatihah",
        "verses_count": 7,
        "revelation_type": "Meccan",
        "revelation_order": 5,
        "pages": (1, 1),
    },
    {
        "name_arabic": "البقرة",
        "name_english": "The Cow",
        "name_transliteration": "Al-Baqarah",
        "verses_count": 286,
        "revelation_type": "Medinan",
        "revelation_order": 87,
        "pages": (2, 49),
    },
    {
        "name_arabic": "آل عمران",
        "name_english": "The Family of Imran",
        "name_transliteration": "Aal-E-Imran",
        "verses_count": 200,
        "revelation_type": "Medinan",
        "revelation_order": 89,
        "pages": (50, 76),
    },
    {
        "name_arabic": "النساء",
        "name_english": "The Women",
        "name_transliteration": "An-Nisa",
        "verses_count": 176,
        "revelation_type": "Medinan",
        "revelation_order": 92,
        "pages": (77, 106),
    },
    {
        "name_arabic": "المائدة",
        "name_english": "The Table Spread",
        "name_transliteration": "Al-Ma'idah",
        "verses_count": 120,
        "revelation_type": "Medinan",
        "revelation_order": 112,
        "pages": (106, 127),
    },
    {
        "name_arabic": "الأنعام",
        "name_english": "The Cattle",
        "name_transliteration": "Al-An'am",
        "verses_count": 165,
        "revelation_type": "Meccan",
        "revelation_order": 55,
        "pages": (128, 150),
    },
    {
        "name_arabic": "الأعراف",
        "name_english": "The Heights",
        "name_transliteration": "Al-A'raf",
        "verses_count": 206,
        "revelation_type": "Meccan",
        "revelation_order": 39,
        "pages": (151, 176),
    },
    {
        "name_arabic": "الأنفال",
        "name_english": "The Spoils of War",
        "name_transliteration": "Al-Anfal",
        "verses_count": 75,
        "revelation_type": "Medinan",
        "revelation_order": 88,
        "pages": (177, 186),
    },
    {
        "name_arabic": "التوبة",
        "name_english": "The Repentance",
        "name_transliteration": "At-Tawbah",
        "verses_count": 129,
        "revelation_type": "Medinan",
        "revelation_order": 113,
        "pages": (187, 207),
    },
    {
        "name_arabic": "يونس",
        "name_english": "Jonah",
        "name_transliteration": "Yunus",
        "verses_count": 109,
        "revelation_type": "Meccan",
        "revelation_order": 51,
        "pages": (208, 221),
    },
    {
        "name_arabic": "هود",
        "name_english": "Hud",
        "name_transliteration": "Hud",
        "verses_count": 123,
        "revelation_type": "Meccan",
        "revelation_order": 52,
        "pages": (221, 235),
    },
    {
        "name_arabic": "يوسف",
        "name_english": "Joseph",
        "name_transliteration": "Yusuf",
        "verses_count": 111,
        "revelation_type": "Meccan",
        "revelation_order": 53,
        "pages": (235, 248),
    },
    {
        "name_arabic": "الرعد",
        "name_english": "The Thunder",
        "name_transliteration": "Ar-Ra'd",
        "verses_count": 43,
        "revelation_type": "Medinan",
        "revelation_order": 96,
        "pages": (249, 255),
    },
    {
        "name_arabic": "إبراهيم",
        "name_english": "Abraham",
        "name_transliteration": "Ibrahim",
        "verses_count": 52,
        "revelation_type": "Meccan",
        "revelation_order": 72,
        "pages": (255, 261),
    },
    {
        "name_arabic": "الحجر",
        "name_english": "The Rocky Tract",
        "name_transliteration": "Al-Hijr",
        "verses_count": 99,
        "revelation_type": "Meccan",
        "revelation_order": 54,
        "pages": (262, 267),
    },
    {
        "name_arabic": "النحل",
        "name_english": "The Bee",
        "name_transliteration": "An-Nahl",
        "verses_count": 128,
        "revelation_type": "Meccan",
        "revelation_order": 70,
        "pages": (267, 281),
    },
    {
        "name_arabic": "الإسراء",
        "name_english": "The Night Journey",
        "name_transliteration": "Al-Isra",
        "verses_count": 111,
        "revelation_type": "Meccan",
        "revelation_order": 50,
        "pages": (282, 293),
    },
    {
        "name_arabic": "الكهف",
        "name_english": "The Cave",
        "name_transliteration": "Al-Kahf",
        "verses_count": 110,
        "revelation_type": "Meccan",
        "revelation_order": 69,
        "pages": (293, 304),
    },
    {
        "name_arabic": "مريم",
        "name_english": "Mary",
        "name_transliteration": "Maryam",
        "verses_count": 98,
        "revelation_type": "Meccan",
        "revelation_order": 44,
        "pages": (305, 312),
    },
    {
        "name_arabic": "طه",
        "name_english": "Ta-Ha",
        "name_transliteration": "Ta-Ha",
        "verses_count": 135,
        "revelation_type": "Meccan",
        "revelation_order": 45,
        "pages": (312, 321),
    },
    {
        "name_arabic": "الأنبياء",
        "name_english": "The Prophets",
        "name_transliteration": "Al-Anbiya",
        "verses_count": 112,
        "revelation_type": "Meccan",
        "revelation_order": 73,
        "pages": (322, 331),
    },
    {
        "name_arabic": "الحج",
        "name_english": "The Pilgrimage",
        "name_transliteration": "Al-Hajj",
        "verses_count": 78,
        "revelation_type": "Medinan",
        "revelation_order": 103,
        "pages": (332, 341),
    },
    {
        "name_arabic": "المؤمنون",
        "name_english": "The Believers",
        "name_transliteration": "Al-Mu'minun",
        "verses_count": 118,
        "revelation_type": "Meccan",
        "revelation_order": 74,
        "pages": (342, 349),
    },
    {
        "name_arabic": "النور",
        "name_english": "The Light",
        "name_transliteration": "An-Nur",
        "verses_count": 64,
        "revelation_type": "Medinan",
        "revelation_order": 102,
        "pages": (350, 359),
    },
    {
        "name_arabic": "الفرقان",
        "name_english": "The Criterion",
        "name_transliteration": "Al-Furqan",
        "verses_count": 77,
        "revelation_type": "Meccan",
        "revelation_order": 42,
        "pages": (359, 366),
    },
    {
        "name_arabic": "الشعراء",
        "name_english": "The Poets",
        "name_transliteration": "Ash-Shu'ara",
        "verses_count": 227,
        "revelation_type": "Meccan",
        "revelation_order": 47,
        "pages": (367, 376),
    },
    {
        "name_arabic": "النمل",
        "name_english": "The Ant",
        "name_transliteration": "An-Naml",
        "verses_count": 93,
        "revelation_type": "Meccan",
        "revelation_order": 48,
        "pages": (377, 385),
    },
    {
        "name_arabic": "القصص",
        "name_english": "The Stories",
        "name_transliteration": "Al-Qasas",
        "verses_count": 88,
        "revelation_type": "Meccan",
        "revelation_order": 49,
        "pages": (385, 396),
    },
    {
        "name_arabic": "العنكبوت",
        "name_english": "The Spider",
        "name_transliteration": "Al-Ankabut",
        "verses_count": 69,
        "revelation_type": "Meccan",
        "revelation_order": 85,
        "pages": (396, 404),
    },
    {
        "name_arabic": "الروم",
        "name_english": "The Romans",
        "name_transliteration": "Ar-Rum",
        "verses_count": 60,
        "revelation_type": "Meccan",
        "revelation_order": 84,
        "pages": (404, 410),
    },
    {
        "name_arabic": "لقمان",
        "name_english": "Luqman",
        "name_transliteration": "Luqman",
        "verses_count": 34,
        "revelation_type": "Meccan",
        "revelation_order": 57,
        "pages": (411, 414),
    },
    {
        "name_arabic": "السجدة",
        "name_english": "The Prostration",
        "name_transliteration": "As-Sajdah",
        "verses_count": 30,
        "revelation_type": "Meccan",
        "revelation_order": 75,
        "pages": (415, 417),
    },
    {
        "name_arabic": "الأحزاب",
        "name_english": "The Combined Forces",
        "name_transliteration": "Al-Ahzab",
        "verses_count": 73,
        "revelation_type": "Medinan",
        "revelation_order": 90,
        "pages": (418, 427),
    },
    {
        "name_arabic": "سبأ",
        "name_english": "Sheba",
        "name_transliteration": "Saba",
        "verses_count": 54,
        "revelation_type": "Meccan",
        "revelation_order": 58,
        "pages": (428, 434),
    },
    {
        "name_arabic": "فاطر",
        "name_english": "The Originator",
        "name_transliteration": "Fatir",
        "verses_count": 45,
        "revelation_type": "Meccan",
        "revelation_order": 43,
        "pages": (434, 440),
    },
    {
        "name_arabic": "يس",
        "name_english": "Ya-Sin",
        "name_transliteration": "Ya-Sin",
        "verses_count": 83,
        "revelation_type": "Meccan",
        "revelation_order": 41,
        "pages": (440, 445),
    },
    {
        "name_arabic": "الصافات",
        "name_english": "Those Ranged in Ranks",
        "name_transliteration": "As-Saffat",
        "verses_count": 182,
        "revelation_type": "Meccan",
        "revelation_order": 56,
        "pages": (446, 452),
    },
    {
        "name_arabic": "ص",
        "name_english": "Sad",
        "name_transliteration": "Sad",
        "verses_count": 88,
        "revelation_type": "Meccan",
        "revelation_order": 38,
        "pages": (453, 458),
    },
    {
        "name_arabic": "الزمر",
        "name_english": "The Groups",
        "name_transliteration": "Az-Zumar",
        "verses_count": 75,
        "revelation_type": "Meccan",
        "revelation_order": 59,
        "pages": (458, 467),
    },
    {
        "name_arabic": "غافر",
        "name_english": "The Forgiver",
        "name_transliteration": "Ghafir",
        "verses_count": 85,
        "revelation_type": "Meccan",
        "revelation_order": 60,
        "pages": (467, 476),
    },
    {
        "name_arabic": "فصلت",
        "name_english": "Explained in Detail",
        "name_transliteration": "Fussilat",
        "verses_count": 54,
        "revelation_type": "Meccan",
        "revelation_order": 61,
        "pages": (477, 482),
    },
    {
        "name_arabic": "الشورى",
        "name_english": "The Consultation",
        "name_transliteration": "Ash-Shura",
        "verses_count": 53,
        "revelation_type": "Meccan",
        "revelation_order": 62,
        "pages": (483, 489),
    },
    {
        "name_arabic": "الزخرف",
        "name_english": "The Gold Adornment",
        "name_transliteration": "Az-Zukhruf",
        "verses_count": 89,
        "revelation_type": "Meccan",
        "revelation_order": 63,
        "pages": (489, 495),
    },
    {
        "name_arabic": "الدخان",
        "name_english": "The Smoke",
        "name_transliteration": "Ad-Dukhan",
        "verses_count": 59,
        "revelation_type": "Meccan",
        "revelation_order": 64,
        "pages": (496, 498),
    },
    {
        "name_arabic": "الجاثية",
        "name_english": "The Kneeling",
        "name_transliteration": "Al-Jathiyah",
        "verses_count": 37,
        "revelation_type": "Meccan",
        "revelation_order": 65,
        "pages": (499, 502),
    },
    {
        "name_arabic": "الأحقاف",
        "name_english": "The Curved Sand-hills",
        "name_transliteration": "Al-Ahqaf",
        "verses_count": 35,
        "revelation_type": "Meccan",
        "revelation_order": 66,
        "pages": (502, 506),
    },
    {
        "name_arabic": "محمد",
        "name_english": "Muhammad",
        "name_transliteration": "Muhammad",
        "verses_count": 38,
        "revelation_type": "Medinan",
        "revelation_order": 95,
        "pages": (507, 510),
    },
    {
        "name_arabic": "الفتح",
        "name_english": "The Victory",
        "name_transliteration": "Al-Fath",
        "verses_count": 29,
        "revelation_type": "Medinan",
        "revelation_order": 111,
        "pages": (511, 515),
    },
    {
        "name_arabic": "الحجرات",
        "name_english": "The Rooms",
        "name_transliteration": "Al-Hujurat",
        "verses_count": 18,
        "revelation_type": "Medinan",
        "revelation_order": 106,
        "pages": (515, 517),
    },
    {
        "name_arabic": "ق",
        "name_english": "Qaf",
        "name_transliteration": "Qaf",
        "verses_count": 45,
        "revelation_type": "Meccan",
        "revelation_order": 34,
        "pages": (518, 520),
    },
    {
        "name_arabic": "الذاريات",
        "name_english": "The Winnowing Winds",
        "name_transliteration": "Adh-Dhariyat",
        "verses_count": 60,
        "revelation_type": "Meccan",
        "revelation_order": 67,
        "pages": (520, 523),
    },
    {
        "name_arabic": "الطور",
        "name_english": "The Mount",
        "name_transliteration": "At-Tur",
        "verses_count": 49,
        "revelation_type": "Meccan",
        "revelation_order": 76,
        "pages": (523, 525),
    },
    {
        "name_arabic": "النجم",
        "name_english": "The Star",
        "name_transliteration": "An-Najm",
        "verses_count": 62,
        "revelation_type": "Meccan",
        "revelation_order": 23,
        "pages": (526, 528),
    },
    {
        "name_arabic": "القمر",
        "name_english": "The Moon",
        "name_transliteration": "Al-Qamar",
        "verses_count": 55,
        "revelation_type": "Meccan",
        "revelation_order": 37,
        "pages": (528, 531),
    },
    {
        "name_arabic": "الرحمن",
        "name_english": "The Most Gracious",
        "name_transliteration": "Ar-Rahman",
        "verses_count": 78,
        "revelation_type": "Medinan",
        "revelation_order": 97,
        "pages": (531, 534),
    },
    {
        "name_arabic": "الواقعة",
        "name_english": "The Inevitable",
        "name_transliteration": "Al-Waqi'ah",
        "verses_count": 96,
        "revelation_type": "Meccan",
        "revelation_order": 46,
        "pages": (534, 537),
    },
    {
        "name_arabic": "الحديد",
        "name_english": "The Iron",
        "name_transliteration": "Al-Hadid",
        "verses_count": 29,
        "revelation_type": "Medinan",
        "revelation_order": 94,
        "pages": (537, 541),
    },
    {
        "name_arabic": "المجادلة",
        "name_english": "The Pleading Woman",
        "name_transliteration": "Al-Mujadilah",
        "verses_count": 22,
        "revelation_type": "Medinan",
        "revelation_order": 105,
        "pages": (542, 545),
    },
    {
        "name_arabic": "الحشر",
        "name_english": "The Exile",
        "name_transliteration": "Al-Hashr",
        "verses_count": 24,
        "revelation_type": "Medinan",
        "revelation_order": 101,
        "pages": (545, 548),
    },
    {
        "name_arabic": "الممتحنة",
        "name_english": "She That is to be Examined",
        "name_transliteration": "Al-Mumtahanah",
        "verses_count": 13,
        "revelation_type": "Medinan",
        "revelation_order": 91,
        "pages": (549, 551),
    },
    {
        "name_arabic": "الصف",
        "name_english": "The Ranks",
        "name_transliteration": "As-Saff",
        "verses_count": 14,
        "revelation_type": "Medinan",
        "revelation_order": 109,
        "pages": (551, 552),
    },
    {
        "name_arabic": "الجمعة",
        "name_english": "Friday",
        "name_transliteration": "Al-Jumu'ah",
        "verses_count": 11,
        "revelation_type": "Medinan",
        "revelation_order": 110,
        "pages": (553, 554),
    },
    {
        "name_arabic": "المنافقون",
        "name_english": "The Hypocrites",
        "name_transliteration": "Al-Munafiqun",
        "verses_count": 11,
        "revelation_type": "Medinan",
        "revelation_order": 104,
        "pages": (554, 555),
    },
    {
        "name_arabic": "التغابن",
        "name_english": "The Mutual Disillusion",
        "name_transliteration": "At-Taghabun",
        "verses_count": 18,
        "revelation_type": "Medinan",
        "revelation_order": 108,
        "pages": (556, 557),
    },
    {
        "name_arabic": "الطلاق",
        "name_english": "The Divorce",
        "name_transliteration": "At-Talaq",
        "verses_count": 12,
        "revelation_type": "Medinan",
        "revelation_order": 99,
        "pages": (558, 559),
    },
    {
        "name_arabic": "التحريم",
        "name_english": "The Prohibition",
        "name_transliteration": "At-Tahrim",
        "verses_count": 12,
        "revelation_type": "Medinan",
        "revelation_order": 107,
        "pages": (560, 561),
    },
    {
        "name_arabic": "الملك",
        "name_english": "The Sovereignty",
        "name_transliteration": "Al-Mulk",
        "verses_count": 30,
        "revelation_type": "Meccan",
        "revelation_order": 77,
        "pages": (562, 564),
    },
    {
        "name_arabic": "القلم",
        "name_english": "The Pen",
        "name_transliteration": "Al-Qalam",
        "verses_count": 52,
        "revelation_type": "Meccan",
        "revelation_order": 2,
        "pages": (564, 566),
    },
    {
        "name_arabic": "الحاقة",
        "name_english": "The Reality",
        "name_transliteration": "Al-Haqqah",
        "verses_count": 52,
        "revelation_type": "Meccan",
        "revelation_order": 78,
        "pages": (566, 568),
    },
    {
        "name_arabic": "المعارج",
        "name_english": "The Ascending Stairways",
        "name_transliteration": "Al-Ma'arij",
        "verses_count": 44,
        "revelation_type": "Meccan",
        "revelation_order": 79,
        "pages": (568, 570),
    },
    {
        "name_arabic": "نوح",
        "name_english": "Noah",
        "name_transliteration": "Nuh",
        "verses_count": 28,
        "revelation_type": "Meccan",
        "revelation_order": 71,
        "pages": (570, 571),
    },
    {
        "name_arabic": "الجن",
        "name_english": "The Jinn",
        "name_transliteration": "Al-Jinn",
        "verses_count": 28,
        "revelation_type": "Meccan",
        "revelation_order": 40,
        "pages": (572, 573),
    },
    {
        "name_arabic": "المزمل",
        "name_english": "The Enshrouded One",
        "name_transliteration": "Al-Muzzammil",
        "verses_count": 20,
        "revelation_type": "Meccan",
        "revelation_order": 3,
        "pages": (574, 575),
    },
    {
        "name_arabic": "المدثر",
        "name_english": "The Cloaked One",
        "name_transliteration": "Al-Muddaththir",
        "verses_count": 56,
        "revelation_type": "Meccan",
        "revelation_order": 4,
        "pages": (575, 577),
    },
    {
        "name_arabic": "القيامة",
        "name_english": "The Resurrection",
        "name_transliteration": "Al-Qiyamah",
        "verses_count": 40,
        "revelation_type": "Meccan",
        "revelation_order": 31,
        "pages": (577, 578),
    },
    {
        "name_arabic": "الإنسان",
        "name_english": "Man",
        "name_transliteration": "Al-Insan",
        "verses_count": 31,
        "revelation_type": "Medinan",
        "revelation_order": 98,
        "pages": (578, 580),
    },
    {
        "name_arabic": "المرسلات",
        "name_english": "The Emissaries",
        "name_transliteration": "Al-Mursalat",
        "verses_count": 50,
        "revelation_type": "Meccan",
        "revelation_order": 33,
        "pages": (580, 581),
    },
    {
        "name_arabic": "النبأ",
        "name_english": "The Tidings",
        "name_transliteration": "An-Naba",
        "verses_count": 40,
        "revelation_type": "Meccan",
        "revelation_order": 80,
        "pages": (582, 583),
    },
    {
        "name_arabic": "النازعات",
        "name_english": "Those Who Drag Forth",
        "name_transliteration": "An-Nazi'at",
        "verses_count": 46,
        "revelation_type": "Meccan",
        "revelation_order": 81,
        "pages": (583, 584),
    },
    {
        "name_arabic": "عبس",
        "name_english": "He Frowned",
        "name_transliteration": "Abasa",
        "verses_count": 42,
        "revelation_type": "Meccan",
        "revelation_order": 24,
        "pages": (585, 586),
    },
    {
        "name_arabic": "التكوير",
        "name_english": "The Overthrowing",
        "name_transliteration": "At-Takwir",
        "verses_count": 29,
        "revelation_type": "Meccan",
        "revelation_order": 7,
        "pages": (586, 586),
    },
    {
        "name_arabic": "الانفطار",
        "name_english": "The Cleaving",
        "name_transliteration": "Al-Infitar",
        "verses_count": 19,
        "revelation_type": "Meccan",
        "revelation_order": 82,
        "pages": (587, 587),
    },
    {
        "name_arabic": "المطففين",
        "name_english": "The Defrauding",
        "name_transliteration": "Al-Mutaffifin",
        "verses_count": 36,
        "revelation_type": "Meccan",
        "revelation_order": 86,
        "pages": (587, 589),
    },
    {
        "name_arabic": "الانشقاق",
        "name_english": "The Splitting Open",
        "name_transliteration": "Al-Inshiqaq",
        "verses_count": 25,
        "revelation_type": "Meccan",
        "revelation_order": 83,
        "pages": (589, 589),
    },
    {
        "name_arabic": "البروج",
        "name_english": "The Mansions of the Stars",
        "name_transliteration": "Al-Buruj",
        "verses_count": 22,
        "revelation_type": "Meccan",
        "revelation_order": 27,
        "pages": (590, 590),
    },
    {
        "name_arabic": "الطارق",
        "name_english": "The Morning Star",
        "name_transliteration": "At-Tariq",
        "verses_count": 17,
        "revelation_type": "Meccan",
        "revelation_order": 36,
        "pages": (591, 591),
    },
    {
        "name_arabic": "الأعلى",
        "name_english": "The Most High",
        "name_transliteration": "Al-A'la",
        "verses_count": 19,
        "revelation_type": "Meccan",
        "revelation_order": 8,
        "pages": (591, 592),
    },
    {
        "name_arabic": "الغاشية",
        "name_english": "The Overwhelming",
        "name_transliteration": "Al-Ghashiyah",
        "verses_count": 26,
        "revelation_type": "Meccan",
        "revelation_order": 68,
        "pages": (592, 592),
    },
    {
        "name_arabic": "الفجر",
        "name_english": "The Dawn",
        "name_transliteration": "Al-Fajr",
        "verses_count": 30,
        "revelation_type": "Meccan",
        "revelation_order": 10,
        "pages": (593, 594),
    },
    {
        "name_arabic": "البلد",
        "name_english": "The City",
        "name_transliteration": "Al-Balad",
        "verses_count": 20,
        "revelation_type": "Meccan",
        "revelation_order": 35,
        "pages": (594, 594),
    },
    {
        "name_arabic": "الشمس",
        "name_english": "The Sun",
        "name_transliteration": "Ash-Shams",
        "verses_count": 15,
        "revelation_type": "Meccan",
        "revelation_order": 26,
        "pages": (595, 595),
    },
    {
        "name_arabic": "الليل",
        "name_english": "The Night",
        "name_transliteration": "Al-Layl",
        "verses_count": 21,
        "revelation_type": "Meccan",
        "revelation_order": 9,
        "pages": (595, 596),
    },
    {
        "name_arabic": "الضحى",
        "name_english": "The Morning Hours",
        "name_transliteration": "Ad-Duha",
        "verses_count": 11,
        "revelation_type": "Meccan",
        "revelation_order": 11,
        "pages": (596, 596),
    },
    {
        "name_arabic": "الشرح",
        "name_english": "The Relief",
        "name_transliteration": "Ash-Sharh",
        "verses_count": 8,
        "revelation_type": "Meccan",
        "revelation_order": 12,
        "pages": (596, 596),
    },
    {
        "name_arabic": "التين",
        "name_english": "The Fig",
        "name_transliteration": "At-Tin",
        "verses_count": 8,
        "revelation_type": "Meccan",
        "revelation_order": 28,
        "pages": (597, 597),
    },
    {
        "name_arabic": "العلق",
        "name_english": "The Clot",
        "name_transliteration": "Al-Alaq",
        "verses_count": 19,
        "revelation_type": "Meccan",
        "revelation_order": 1,
        "pages": (597, 597),
    },
    {
        "name_arabic": "القدر",
        "name_english": "The Power",
        "name_transliteration": "Al-Qadr",
        "verses_count": 5,
        "revelation_type": "Meccan",
        "revelation_order": 25,
        "pages": (598, 598),
    },
    {
        "name_arabic": "البينة",
        "name_english": "The Clear Proof",
        "name_transliteration": "Al-Bayyinah",
        "verses_count": 8,
        "revelation_type": "Medinan",
        "revelation_order": 100,
        "pages": (598, 599),
    },
    {
        "name_arabic": "الزلزلة",
        "name_english": "The Earthquake",
        "name_transliteration": "Az-Zalzalah",
        "verses_count": 8,
        "revelation_type": "Medinan",
        "revelation_order": 93,
        "pages": (599, 599),
    },
    {
        "name_arabic": "العاديات",
        "name_english": "The Courser",
        "name_transliteration": "Al-Adiyat",
        "verses_count": 11,
        "revelation_type": "Meccan",
        "revelation_order": 14,
        "pages": (599, 600),
    },
    {
        "name_arabic": "القارعة",
        "name_english": "The Calamity",
        "name_transliteration": "Al-Qari'ah",
        "verses_count": 11,
        "revelation_type": "Meccan",
        "revelation_order": 30,
        "pages": (600, 600),
    },
    {
        "name_arabic": "التكاثر",
        "name_english": "The Rivalry in World Increase",
        "name_transliteration": "At-Takathur",
        "verses_count": 8,
        "revelation_type": "Meccan",
        "revelation_order": 16,
        "pages": (600, 600),
    },
    {
        "name_arabic": "العصر",
        "name_english": "The Declining Day",
        "name_transliteration": "Al-Asr",
        "verses_count": 3,
        "revelation_type": "Meccan",
        "revelation_order": 13,
        "pages": (601, 601),
    },
    {
        "name_arabic": "الهمزة",
        "name_english": "The Traducer",
        "name_transliteration": "Al-Humazah",
        "verses_count": 9,
        "revelation_type": "Meccan",
        "revelation_order": 32,
        "pages": (601, 601),
    },
    {
        "name_arabic": "الفيل",
        "name_english": "The Elephant",
        "name_transliteration": "Al-Fil",
        "verses_count": 5,
        "revelation_type": "Meccan",
        "revelation_order": 19,
        "pages": (601, 601),
    },
    {
        "name_arabic": "قريش",
        "name_english": "Quraysh",
        "name_transliteration": "Quraysh",
        "verses_count": 4,
        "revelation_type": "Meccan",
        "revelation_order": 29,
        "pages": (602, 602),
    },
    {
        "name_arabic": "الماعون",
        "name_english": "The Small Kindnesses",
        "name_transliteration": "Al-Ma'un",
        "verses_count": 7,
        "revelation_type": "Meccan",
        "revelation_order": 17,
        "pages": (602, 602),
    },
    {
        "name_arabic": "الكوثر",
        "name_english": "The Abundance",
        "name_transliteration": "Al-Kawthar",
        "verses_count": 3,
        "revelation_type": "Meccan",
        "revelation_order": 15,
        "pages": (602, 602),
    },
    {
        "name_arabic": "الكافرون",
        "name_english": "The Disbelievers",
        "name_transliteration": "Al-Kafirun",
        "verses_count": 6,
        "revelation_type": "Meccan",
        "revelation_order": 18,
        "pages": (603, 603),
    },
    {
        "name_arabic": "النصر",
        "name_english": "The Divine Support",
        "name_transliteration": "An-Nasr",
        "verses_count": 3,
        "revelation_type": "Medinan",
        "revelation_order": 114,
        "pages": (603, 603),
    },
    {
        "name_arabic": "المسد",
        "name_english": "The Palm Fiber",
        "name_transliteration": "Al-Masad",
        "verses_count": 5,
        "revelation_type": "Meccan",
        "revelation_order": 6,
        "pages": (603, 603),
    },
    {
        "name_arabic": "الإخلاص",
        "name_english": "The Sincerity",
        "name_transliteration": "Al-Ikhlas",
        "verses_count": 4,
        "revelation_type": "Meccan",
        "revelation_order": 22,
        "pages": (604, 604),
    },
    {
        "name_arabic": "الفلق",
        "name_english": "The Daybreak",
        "name_transliteration": "Al-Falaq",
        "verses_count": 5,
        "revelation_type": "Meccan",
        "revelation_order": 20,
        "pages": (604, 604),
    },
    {
        "name_arabic": "الناس",
        "name_english": "Mankind",
        "name_transliteration": "An-Nas",
        "verses_count": 6,
        "revelation_type": "Meccan",
        "revelation_order": 21,
        "pages": (604, 604),
    },
)

RECITER_INFO = {
    "alafasy": {
        "name_arabic": "مشاري العفاسي",
        "name_english": "Mishary Rashid Alafasy",
        "style": "Murattal",
        "bitrate": 128,
    },
    "husary": {
        "name_arabic": "محمود خليل الحصري",
        "name_english": "Mahmoud Khalil Al-Husary",
        "style": "Murattal",
        "bitrate": 128,
    },
    "minshawi": {
        "name_arabic": "محمد صديق المنشاوي",
        "name_english": "Muhammad Siddiq Al-Minshawi",
        "style": "Mujawwad",
        "bitrate": 128,
    },
    "sudais": {
        "name_arabic": "عبد الرحمن السديس",
        "name_english": "Abdur-Rahman As-Sudais",
        "style": "Murattal",
        "bitrate": 128,
    },
    "abdulbasit": {
        "name_arabic": "عبد الباسط عبد الصمد",
        "name_english": "Abdul Basit Abdul Samad",
        "style": "Mujawwad",
        "bitrate": 128,
    },
    "ghamdi": {
        "name_arabic": "سعد الغامدي",
        "name_english": "Saad Al-Ghamdi",
        "style": "Murattal",
        "bitrate": 128,
    },
    "ajamy": {
        "name_arabic": "أحمد العجمي",
        "name_english": "Ahmad Al-Ajamy",
        "style": "Murattal",
        "bitrate": 128,
    },
    "shuraym": {
        "name_arabic": "سعود الشريم",
        "name_english": "Saud Ash-Shuraym",
        "style": "Murattal",
        "bitrate": 128,
    },
    "basfar": {
        "name_arabic": "عبد الله بصفر",
        "name_english": "Abdullah Basfar",
        "style": "Murattal",
        "bitrate": 128,
    },
    "shaatree": {
        "name_arabic": "أبو بكر الشاطري",
        "name_english": "Abu Bakr Ash-Shaatree",
        "style": "Murattal",
        "bitrate": 128,
    },
    "hudhaify": {
        "name_arabic": "علي الحذيفي",
        "name_english": "Ali Al-Hudhaify",
        "style": "Murattal",
        "bitrate": 128,
    },
    "saad_alghamdi": {
        "name_arabic": "سعد الغامدي",
        "name_english": "Saad Al-Ghamdi",
        "style": "Murattal",
        "bitrate": 128,
    },
    "ali_jaber": {
        "name_arabic": "علي جابر",
        "name_english": "Ali Jaber",
        "style": "Murattal",
        "bitrate": 128,
    },
    "nasser_alqatami": {
        "name_arabic": "ناصر القطامي",
        "name_english": "Nasser Al-Qatami",
        "style": "Murattal",
        "bitrate": 128,
    },
    "yasser_aldosari": {
        "name_arabic": "ياسر الدوسري",
        "name_english": "Yasser Ad-Dosari",
        "style": "Murattal",
        "bitrate": 128,
    },
    "maher_almuaiqly": {
        "name_arabic": "ماهر المعيقلي",
        "name_english": "Maher Al-Muaiqly",
        "style": "Murattal",
        "bitrate": 128,
    },
    "husary_muallim": {
        "name_arabic": "محمود خليل الحصري - معلم",
        "name_english": "Mahmoud Khalil Al-Husary (Muallim)",
        "style": "Muallim",
        "bitrate": 128,
    },
    "minshawi_murattal": {
        "name_arabic": "محمد صديق المنشاوي - مرتل",
        "name_english": "Muhammad Siddiq Al-Minshawi (Murattal)",
        "style": "Murattal",
        "bitrate": 128,
    },
    "abdulbasit_murattal": {
        "name_arabic": "عبد الباسط عبد الصمد - مرتل",
        "name_english": "Abdul Basit Abdul Samad (Murattal)",
        "style": "Murattal",
        "bitrate": 128,
    },
}

VERSE_COUNTS = tuple(s["verses_count"] for s in SURAH_DATA)
